services:
  nginx:
    container_name: nginx
    image: nginx_image
    build:
      context: requirements/nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception

  wordpress:
    container_name: wp-php
    image: wordpress_image
    build:
      context: requirements/wordpress
    volumes:
      - ./web:/var/www/html
    networks:
      - inception

  maria_db:
    container_name: mariadb
    image: mariadb_image
    build:
      context: requirements/mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge
    